version: "2.3"
 
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
 
  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/index
      - /index/node_modules
    depends_on:
      - mongodb
 
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - server
 
volumes:
  data:
  logs:
 